[sdl]
fullscreen=false
fulldouble=false
fullscreen_mode=original
window_size=1024x768
output=opengl
autolock=true
mouse_sensitivity=100
waitonerror=true
priority=higher,normal
mapperfile=mapper-0.74-3.map
keyboard_layout=us

[dosbox]
machine=svga_s3
captures=capture
memsize=16

[render]
cpu_cycles=max
cpu_cycles_protected=auto
cpu_throttle=1
presentation_mode=dos_rate

[render]
shader=none

[cpu]
core=normal
cputype=386
cpu_cycles=max
cpu_cycles_protected=auto
cpu_throttle=1

[mixer]
nosound=true
rate=44100
blocksize=1024
prebuffer=25

[midi]
mpu401=none
mididevice=none
midiconfig=

[sblaster]
sbtype=none
sbbase=220
irq=7
dma=1
hdma=5
sbmixer=true
oplmode=auto
oplrate=44100

[gus]
gus=false
gusrate=44100
gusbase=240
gusirq=5
gusdma=3
ultradir=C:\ULTRASND

[speaker]
pcspeaker=false
pcrate=44100
tandy=auto
tandyrate=44100
disney=true

[joystick]
joysticktype=none
timed=true
autofire=false
swap34=false
buttonwrap=false

[serial]
serial1=directserial realport:COM1
serial2=disabled
serial3=disabled
serial4=disabled

[dos]
xms=true
ems=true
umb=true
keyboard_layout=us

[ipx]
ipx=false

[autoexec]
mount c dos\msc60
c:
path c:\bin;c:\binr
set INCLUDE=c:\include
set LIB=c:\lib
set PATH=c:\bin;c:\binr